---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      imagePullSecrets:
      - name: regcred
      - name: chinmaynm8
        image: chinmaynm8/dockerhub
        ports:
        - containerPort: 80
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: javawebapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapp
