---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: java-web-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      containers:
      - name: chinmaynm8/dockerhub
        image: chinmaynm8/dockerhub
        ports:
        - containerPort: 8080 
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: java-web-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: java-web-app
